SELECT * FROM HOTEL;
SELECT * FROM HOTEL WHERE CITY="Cali";
SELECT guestName, guestAddress FROM GUEST  WHERE guestCity in (SELECT CITY FROM HOTEL WHERE CITY="Cali") ORDER BY guestName;
SELECT * FROM ROOM WHERE TYPE IN ('Family', 'Double') AND PRICE < 80 ORDER BY PRICE;